#%RAML 0.8

title: Pets API

baseUri: http://my-pets.net/

schemas:
  - pets: >
      {
        "type": "string"
      }
mediaType: application/json

/pets:
    get:
        responses:
            200:
                body:
                    schema: pets
    post:
        responses:
            200:
